sonar.projectKey=warehouseflow-base
sonar.projectName=WarehouseFlow Base Project
sonar.sourceEncoding=UTF-8

sonar.sources=client/src,server/src
sonar.tests=server/src
sonar.test.inclusions=**/*.test.js,**/*.spec.js

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
